user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "."
    type:     "api"
    prefix:   "/api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/doc"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: FOSUserBundle:Security:loginCheck }
