# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    resource.book:
        parent:    "api.resource"
        arguments: [ "AppBundle\\UserBundle\\Entity\\User" ]
        calls:
           -      method:    "initNormalizationContext"
                  arguments: [ { groups: [ "user_read" ] } ]
           -      method:    "initDenormalizationContext"
                  arguments: [ { groups: [ "user_write" ] } ]
        tags:      [ { name: "api.resource" } ]

#
## Examples of API resource mapping, learn more at
## https://github.com/dunglas/DunglasApiBundle
#    resource.book:
#        parent:    "api.resource"
#        arguments: [ "AppBundle\\Entity\\Book" ]
#        tags:      [ { name: "api.resource" } ]
#
#    resource.person:
#        parent:    "api.resource"
#        arguments: [ "AppBundle\\Entity\\Person" ]
#        tags:      [ { name: "api.resource" } ]
#
#    resource.organization:
#        parent:    "api.resource"
#        arguments: [ "AppBundle\\Entity\\Organization" ]
#        calls:
#            -      [ "initFilters", [ [ "@resource.organization.filter" ] ] ]
#        tags:      [ { name: "api.resource" } ]
#
#    resource.organization.filter:
#        parent:    "api.doctrine.orm.search_filter"
#        arguments: [ { "name": "exact", "url": "partial" } ]

# A typical service
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
